### ISSUE TITLE
Contract Spec: Define XDR (take from CAP-47).

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-sdk#115]

**Comment by leighmcculloch** [comment]
@MonsieurNicolas I'm going to be defining some XDR for the manifest, likely just taking what was in CAP-47, but this XDR won't be part of the transaction protocol yet it seems given that CAP-47 considers it an extension. I want to commit this XDR to the stellar-core repo because I want the XDR to be in the XDR that all SDKs pull in. This XDR would be similar to the overlay XDR, it lives there, it's part of Stellar's XDR, but it isn't part of the transaction/consensus protocol. Are you fine with that? If not, maybe we should move the .x files to their own repo so they aren't stuck to core.

**Comment by MonsieurNicolas** [comment]
This does not make sense to me: extending `SCType` is a protocol change. This will be data "on chain", so it better be managed like a protocol level thing.

So either
* we include those changes in CAP-0047
* or the manifest data is a "pure" `SCVal`, in which case there is no real expectation from the runtime point of view (but I don't think this is what is intended in CAP-0047)

Solution might be "a bit of both": there are certain things that are we need for the runtime (like routing information), so having a "hard spec" for those is clearly better.
Other things fall probably under ecosystem metadata, like if people want to attach arbitrary tags to contracts, that then can be used from contracts or tools --> think of the equivalent of homedomain + hash of a larger manifest about that contract type of thing.

**Comment by leighmcculloch** [comment]
The manifest I'm talking about is a list of functions, it's not other arbitrary metadata.

For example:
```c
enum ContractMetadataType
{
    METADATA_TYPE_V0 = 0
};

union SCType switch (SCValType type)
{
case SCV_U63:
case SCV_U32:
case SCV_I32:
case SCV_STATIC:
    void;
case SCV_OBJECT:
    SCObjectType objType;
case SCV_SYMBOL:
case SCV_BITSET:
case SCV_STATUS:
    void;
};

struct FunctionSignature
{
    SCSymbol function;
    SCType returnType;
    SCType argTypes<10>;
}

union ContractMetadata switch (ContractMetadataType type)
{
case METADATA_TYPE_V0:
    FunctionSignature interface<10>;
};
```

We're likely to end up with the full manifest in the XDR eventually, but at the moment it sounds like core wont use it in v1 which is why it ended up as an extension in CAP-47. I think both @MonsieurNicolas and @jonjove might have suggested we didn't need it in v1? 

Our SDK tooling wants it still. We already put non-protocol data structures that aren't managed by CAPs into the .x files (e.g. overlay), so I don't see how this would be any different. We could put it in a separate .x file like how the overlay types are defined.

If you think the fact the tools want it is enough to include it in CAP-47, great, let's do that. cc @sisuresh 

I agree, the `SCType` should probably be part of the protocol regardless, so imagine that being in the contract.x file, and the rest of the manifest being in a contract-manifest.x file.

**Comment by leighmcculloch** [comment]
The contract spec is now captured in https://github.com/stellar/rs-stellar-xdr/pull/76.
