### ISSUE TITLE
Type: BigInt: Add Debug impl

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-sdk#219]

**Comment by leighmcculloch** [comment]
@jayz22 We'll need functions for getting the binary of a BigInt to display in this Debug, which I assume is dependent on https://github.com/stellar/rs-stellar-contract-env/issues/171.

**Comment by smac711** [comment]
@jayz22 should this issue be assigned to you? and what is the current status?

**Comment by leighmcculloch** [comment]
@jayz22 What's your thought on how to render the BigInt? I was thinking it'd render as base10, but I could see arguments for hex too.

**Comment by jayz22** [comment]
I would prefer base10 too, but you probably know better what's the most useful representation from developer's view. 
It should be an easy switch from hostfn side, we'll be able to pass in a radix to the function to get the digits in any base we want.

**Comment by leighmcculloch** [comment]
Or return binary and let the SDK figure that out.
