### ISSUE TITLE
Test Fwk: Generate ed25519 signing impl for UDTs if contracttype signable present (macros)

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-sdk#241]

**Comment by jonjove** [comment]
This already works pretty nicely, I'm not sure if we actually need to do this.

**Comment by leighmcculloch** [comment]
The goal would be if we want someone to be able to call `message.sign(...)` instead of `theirkey.sign(message)`. I don't feel strongly about keeping this because as you pointed out in a DM the other work we did has made this very ergonomic already. I'll close this.
