### ISSUE TITLE
Test Fwk: Generate another wrap method that calls the contract fn via the env.invoke_function (macros)

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-sdk#243]

**Comment by jonjove** [comment]
Blocked by https://github.com/stellar/rs-stellar-contract-env/issues/106, since it won't be easy for me to test until that is done

**Comment by leighmcculloch** [comment]
This is unblocked, I hope. If when you attempt to do this you find any gaps, please let me know, but I think I have filled all the type conversions. In the end unblocking this was a much huger amount of work than I anticipated, and included: 
- https://github.com/stellar/rs-stellar-contract-env/pull/247 
- https://github.com/stellar/rs-stellar-contract-env/pull/245 
- https://github.com/stellar/rs-stellar-contract-env/issues/106 
- https://github.com/stellar/rs-stellar-contract-sdk/issues/274 
- https://github.com/stellar/rs-stellar-contract-sdk/issues/240
- https://github.com/stellar/rs-stellar-contract-sdk/issues/280

**Comment by jonjove** [comment]
#316 accidentally left this in a relatively unusable state. It's actually usable as of #338.
