### ISSUE TITLE
Evaluate if we should generate external types

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-stellar-contract-sdk#270]
### What problem does your feature solve?

Right now, UDTs can only be used if you have the host machinery available (either linked in, or by being guest). It's hard for me to imagine how this can conveniently be used to, for example, write a light-weight SDK which submits stellar-core transactions for a given contract because the SDK would itself depend on the host to convert UDTs to `ScVal`.

### What would you like to see?

Consider whether we should generate "external" versions of the type. For example, versions that use `std::vec::Vec` instead of `stellar_contract_sdk::Vec`.

### What alternatives are there?

Manually implement those types. Use the UDTs and link in the host.

**Comment by leighmcculloch** [comment]
I think with https://github.com/stellar/rs-stellar-token-contract/issues/45 we decided to not generate external types and just reuse SDK types. Closing because of this, but please reopen if we should still re-evaluate this.
